Repository jungbyungwook/FIONDB, pull requests merged in 2022-12, with the labels that each got.

#14 Feat/player/matchResultButton
  global.d.ts
  next.config.js
  package.json
  src/components/player/MatchRefetchButton.tsx
  src/components/player/MatchResultBox.tsx
  src/components/player/UserProfileBox.tsx
  src/pages/api/hooks/query/useRefetchQuery.tsx
  yarn.lock
Labels: feature, deployed

#9 Featuer/page/player/pick best player
  api/instance.ts
  api/user/getUserAccessId.ts
  api/user/getUserMatch.ts
  api/user/getUserTopTier.ts
  global.d.ts
  hooks/useGetUserAccessId.ts
  hooks/useGetUserRecord.ts
  hooks/useRouterByEnter.tsx
  next.config.js
  package.json
  src/assets/svg/down_arrow.svg
  src/components/Footer.tsx
  src/components/Input.tsx
  src/components/Layout.tsx
  src/components/SearchInput.tsx
  src/components/Title.tsx
  src/components/index.ts
  src/components/player/MatchRefetchButton.tsx
  src/components/player/MatchResultBox.tsx
  src/components/player/UserProfileBox.tsx
  src/components/player/UserTopTierBox.tsx
  src/components/player/badge/BestPlayerBadge.tsx
  src/components/ui/Image/ImageWithFallback.tsx
  src/components/ui/Input/Input.tsx
  src/components/ui/ListItem.tsx
  src/components/ui/bar/PercentBar.tsx
  src/pages/_app.tsx
  src/pages/api/hello.ts
  src/pages/api/hooks/query/useCustomInfiniteQuery.tsx
  src/pages/api/hooks/query/useGetSoccerPlayerName.tsx
  src/pages/api/hooks/query/useGetTopTierQuery.tsx
  src/pages/api/hooks/query/useGetUserProfileQuery.tsx
  src/pages/api/hooks/query/useRefetchQuery.tsx
  src/pages/api/hooks/useGetMetaQuery.tsx
  src/pages/api/hooks/useIntersectionObserver.tsx
  src/pages/api/index.ts
  src/pages/api/player/index.ts
  src/pages/api/player/type.ts
  src/pages/api/user/getUserAccessId.ts
  src/pages/index.tsx
  src/pages/player/[nickName].tsx
  src/pages/player/index.tsx
  src/useCases/changeServerDataIntoRenderData.ts
  src/useCases/getImage.ts
  src/useCases/matchRecordCase.ts
  state/userProfile.ts
  tsconfig.json
  types/DetailObject.ts
  util/chageDate.ts
  util/search.ts
  yarn.lock
Labels: feature, deployed

#15 Fix: '@next/bundle-analyzer' 적용으로 인한 build error
  next.config.js
  src/components/player/UserProfileBox.tsx
  yarn.lock
Labels: bug, deployed

#17 env 설정
  src/pages/_app.tsx
  src/pages/index.tsx
Labels: deployed
