Repository jungbyungwook/FIONDB, pull requests merged in 2023-01, with the labels that each got.

#18 Feat/components/formation: 포메이션 박스 컴포넌트 작업 and 폴더구조 변경
  README.md
  package.json
  src/components/common/Badge/BestPlayerBadge.tsx
  src/components/common/Box/Box.tsx
  src/components/common/SoccerPlayerIcon/index.tsx
  src/components/common/SoccerPlayerImage/index.tsx
  src/components/common/SoccerPlayerName/index.tsx
  src/components/player/Formation/index.tsx
  src/components/player/MatchResultBox.tsx
  src/components/player/MatchResultBox/index.tsx
  src/components/player/MatchResultBox/style.ts
  src/components/player/SoccerPlayer/index.tsx
  src/components/player/SoccerPlayer/style.ts
  src/components/player/UserProfile/ProfileBox/index.tsx
  src/components/player/UserProfile/ProfileBox/style.ts
  src/components/player/UserProfile/TopTierBox/index.tsx
  src/components/player/UserProfile/TopTierBox/style.ts
  src/components/player/UserProfile/index.tsx
  src/components/player/UserProfileBox.tsx
  src/components/player/UserTopTierBox.tsx
  src/components/ui/Image/ImageWithFallback.tsx
  src/components/ui/Input/Input.tsx
  src/constants/position/index.ts
  src/hooks/query/useCustomInfiniteQuery.tsx
  src/hooks/query/useGetTopTierQuery.tsx
  src/hooks/query/useGetUserProfileQuery.tsx
  src/hooks/query/useRefetchQuery.tsx
  src/hooks/query/useSoccerPlayerName.tsx
  src/hooks/useGetMetaQuery.tsx
  src/hooks/useIntersectionObserver.tsx
  src/pages/api/hooks/query/useSoccerPlayerName.tsx
  src/pages/api/player/index.ts
  src/pages/player/[nickName].tsx
  src/useCases/changeServerDataIntoRenderData.ts
  src/useCases/getImage.ts
  src/useCases/getSoccerPlayerNameBySpId.ts
  yarn.lock
Labels: deployed

#21 Fix: default를 넣고 상대방의 경기정보가 넘어오지 않는 경우 early return
  src/useCases/changeServerDataIntoRenderData.ts
Labels: bug, deployed

#25 메인페이지 UI
  public/images/background.png
  public/images/background_old.png
  src/components/Header.tsx
  src/pages/_app.tsx
  src/pages/index.tsx
Labels: deployed

#23 Style/i22 style 전적검색 페이지 디자인 작업
  package.json
  src/assets/svg/profile_background.svg
  src/assets/svg/restart_alt.svg
  src/components/Header.tsx
  src/components/Layout.tsx
  src/components/common/Badge/Badge.tsx
  src/components/common/Badge/GradeBadge.tsx
  src/components/common/Badge/MvpBadge.tsx
  src/components/common/Badge/SeasonBadge.tsx
  src/components/common/Bar/BallPossessionBar.tsx
  src/components/common/Bar/PercentBarCommon.tsx
  src/components/common/Button/Button.tsx
  src/components/common/Button/RefetchButton.tsx
  src/components/common/Chart/WinPercentChart.tsx
  src/components/common/SoccerPlayerImage/index.tsx
  src/components/common/SoccerPlayerName/index.tsx
  src/components/player/Formation/index.tsx
  src/components/player/MatchResultBox/index.tsx
  src/components/player/MatchResultBox/style.ts
  src/components/player/SoccerPlayer/index.tsx
  src/components/player/SoccerPlayer/style.ts
  src/components/player/UserProfile/ProfileBox/index.tsx
  src/components/player/UserProfile/ProfileBox/style.ts
  src/components/player/UserProfile/TopTierBox/index.tsx
  src/components/player/UserProfile/TopTierBox/style.ts
  src/components/player/UserProfile/index.tsx
  src/components/ui/bar/PercentBar.tsx
  src/constants/matchResultText.ts
  src/hooks/useGetMetaQuery.tsx
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/api/hooks/query/useGetSoccerPlayerName.tsx
  src/pages/api/hooks/query/useGetTopTierQuery.tsx
  src/pages/api/hooks/query/useGetUserProfileQuery.tsx
  src/pages/api/hooks/query/useMatchInfiniteQuery.tsx
  src/pages/api/player/index.ts
  src/pages/api/player/type.ts
  src/pages/player/[nickName].tsx
  src/style/color.ts
  src/style/font.ts
  src/style/global.tsx
  src/style/styled.d.ts
  src/style/theme.ts
  src/style/util.ts
  src/types/DetailObject.ts
  src/useCases/changeServerDataIntoRenderData.ts
  src/useCases/getImage.ts
  src/useCases/matchRecordCase.ts
  src/useCases/useCaseMatchSearch.ts
  src/useCases/useCaseUserProfile.ts
  state/userProfile.ts
  util/chageDate.ts
  yarn.lock
Labels: help wanted, deployed, style

#28 header
  public/images/FION.DB.png
  src/components/Header.tsx
Labels: deployed

#27 Style/page/match search
  src/assets/png/soccer_coat.png
  src/assets/svg/arrow.svg
  src/assets/svg/down_arrow.svg
  src/components/Header.tsx
  src/components/common/Box/Box.tsx
  src/components/common/Chart/WinPercentChart.tsx
  src/components/common/Chart/util.ts
  src/components/common/Input/Input.tsx
  src/components/common/SoccerPlayerImage/index.tsx
  src/components/player/Formation/FormationBoard.tsx
  src/components/player/Formation/FormationCoat.tsx
  src/components/player/MatchRefetchButton.tsx
  src/components/player/MatchResultBox/index.tsx
  src/components/player/MatchResultBox/style.ts
  src/components/player/SoccerPlayer/index.tsx
  src/components/player/SoccerPlayer/style.ts
  src/components/player/UserProfile/ProfileBox/index.tsx
  src/components/player/UserProfile/TopTierBox/index.tsx
  src/components/player/UserProfile/TopTierBox/style.ts
  src/components/player/UserProfile/UserChartBox.tsx
  src/components/player/UserProfile/index.tsx
  src/constants/position/index.ts
  src/hooks/useStatisticsMatch.tsx
  src/pages/index.tsx
  src/pages/player/[nickName].tsx
  src/style/color.ts
  src/style/keyframes.ts
  src/useCases/changeServerDataIntoRenderData.ts
  src/useCases/matchRecordCase.ts
  src/useCases/useCaseMatchSearch.ts
  src/useCases/useCaseUserProfile.ts
  src/utils/getSoccerPlayerImageSrc.tsx
Labels: feature, deployed

#30 랭킹 페이지 UI
  src/pages/ranking/index.tsx
Labels: deployed

#32 Feat: seo를 위해 meta tag 적용
  src/components/common/HeadMeta/HeadMeta.tsx
  src/pages/_document.tsx
Labels: deployed
